project:
  type: website
  output-dir: docs    # <- add / change this line
  render: 
  - DALEX_tidymodels_example.qmd
  - Random_Forest_SHAP_Analysis.qmd

execute:
  echo: true
  python:
    version: "r-reticulate"
    
website:
  back-to-top-navigation: true
  page-navigation: true
  title: "HDS MSc - Module 3 - XAI"
  navbar:
    background: primary
    search: true
    left:
      - text: "Explainable AI"
        file: DALEX_tidymodels_example.qmd
 
  sidebar:
    - title: "Explainable AI"
      contents:
        #- Extra.qmd 
        - Random_Forest_SHAP_Analysis.qmd
        - DALEX_tidymodels_example.qmd
  
  page-footer: 
    left: "Copyright 2025, Laura Bravo" 
    background: light

    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
   # code-fold: true
    code-tools: true
    code-link: true

editor: visual

